### ISSUE TITLE
[BUG] Incorrect additional_dependencies documentation to run prospector as a pre-commit hook with mypy support

### ISSUE THREAD

**Issue by jdechicchis** [landscapeio/prospector#633]
**Describe the bug**

The documentation for `additional_dependencies` to run prospector as a pre-commit hook with mypy support appears incorrect.

**To Reproduce**

Follow the instructions at https://github.com/landscapeio/prospector/blob/master/docs/pre-commit.rst with pre-commit config:
```
- repo: https://github.com/PyCQA/prospector
  rev: 1.10.0
  hooks:
  - id: prospector
    additional_dependencies:
    - .[with_mypy]
    args: [--with-tool=mypy]
```

Run pre-commit and get error:
```
cannot run tool mypy as support was not installed.
Please install by running 'pip install prospector[with_mypy]'
```

Now change pre-commit config to (note the change in underscore `with_mypy` to  hyphen `with-mypy`):
```
- repo: https://github.com/PyCQA/prospector
  rev: 1.10.0
  hooks:
  - id: prospector
    additional_dependencies:
    - .[with-mypy]
    args: [--with-tool=mypy]
```

pre-commit runs as expected

**Expected behavior**

Following the docs should lead to running prospector with mypy support in pre-commit without error.

**Environment (please complete the following information):**

- OS: macOS
- Prospector version: `1.10.2`
- Python version: `3.11.5`
- pre-commit version: `3.4.0`

**Additional context**

Happy to make a PR to update the docs!
