### ISSUE TITLE
[FEATURE REQUEST] Baseline generation

### ISSUE THREAD

**Issue by gms8994** [landscapeio/prospector#662]
**Is your feature request related to a problem? Please describe.**

When adding prospector to an existing codebase, many errors may appear, and many of them may not be immediately solvable. 

**Describe the solution you'd like**

It would be nice if a baseline file could be generated which would be the errors to ignore going forward. Any changes to the errors reported as it relates to the baseline could be considered an error. See https://phpstan.org/user-guide/baseline for an example.

**Describe alternatives you've considered**

None

**Comment by sbrunner** [comment]
phpstand example file: https://github.com/coenjacobs/mozart/pull/153/files#diff-995edee38ad4f8387e58ebd52c31bcc04c56cc2448d331b1cf5e0b35c57b9efa

Proposed file:
```yaml
files:
  <relative file name>:
    tools:
      <tool name>:
        errors:
          <error code>: 
            number: <number>
```
